# Traefik Configuration
# Configuration principale pour le reverse proxy

# API et Dashboard
api:
  dashboard: true
  insecure: true

# Providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: dgtt-network

# Entry Points
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

# Certificate Resolvers
certificatesResolvers:
  letsencrypt:
    acme:
      tlsChallenge: {}
      email: admin@dgtt.fr
      storage: /letsencrypt/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory

# Logging
log:
  level: INFO
  filePath: "/var/log/traefik.log"

accessLog:
  filePath: "/var/log/access.log"
  format: json

# Metrics
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true

# Ping
ping:
  entryPoint: "traefik"
